project:
  type: website

execute:
  freeze: auto

website:
  title: "Keller Group Lab Manual"
  repo-url: https://github.com/keller-lab/web-manual
  issue-url: https://github.com/keller-lab/web-manual/issues
  repo-actions: [edit, issue]
  page-footer:
    right:
      - icon: github
        href: https://github.com/keller-lab
        aria-label: Keller Lab GitHub
  navbar:
      background: light
      title: false
      left:
       - text: "Welcome!"
         href: index.qmd
       - text: "Lab Values"
         href: docs/lab-values/index.qmd
       - text: "Onboarding"
         href: docs/onboarding/index.qmd
       - text: "Guide"
         href: docs/guide/index.qmd
      tools:
       - icon: github
         menu:
          - text: Source Code
            href:  https://github.com/keller-lab/web-manual
          - text: Report a Bug
            href:  https://github.com/keller-lab/web-manual/issues

  sidebar:
    - id: onboarding
      collapse-level: 1
      contents:
        - section: "Onboarding"
          href: docs/onboarding/index.qmd
          contents:
            - text: "Checklists"
              href: docs/checklists.qmd
            - text: "Resources"
              href: docs/resources.qmd
              
    - id: guide
      collapse-level: 1
      contents:
        - section: "Guide"
          href: docs/guide/index.qmd
          contents:
           - section: "Data Analysis"
             contents:
              - text: "Our Approach"
                href: docs/analysis/our-approach.qmd
              - text: "Common GitHub Use Cases"
                href: docs/analysis/lab-github.qmd
           - section: "Science Communication"
             contents: 
              - text: "Our Goals"
                href: docs/sci-comm/our-goals.qmd
              - text: "Presentations"
                href: docs/sci-comm/presentation-guidelines.qmd
           - section: "Learning Materials"
             contents: 
              - text: Reading Lists
                href: docs/materials/reading-list.qmd
              - text: Repositories
                href: docs/materials/reproduce-repos.qmd
           - text: "Professional Development"
             href: docs/prof-dev.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

